### ISSUE TITLE
Setting Attributes

### ISSUE THREAD

**Issue by joeadam** [hgrecco/pyvisa#117]
This may just be me missing the right way to do it.

I want to set the VI_ATTR_TERM_CHAR_EN to True.  However I don't seem to be able to write to it, I always get an error about incorrect type.  I've tried True, 1 and pyvisa.constants.VI_TRUE

The resource I working with is a GPIB instrument, which responds, but doesn't seem to terminate the message correctly (so NI Spy shows the reply bytes in the buffer, with termination character, but the call timesout).

**Comment by hgrecco** [comment]
Please notice that the constant is called `VI_ATTR_TERMCHAR_EN`. I guess is a typo here, not in you code so I am answering anyway.

The most general way to set a VISA attribute is:
```python
inst.set_visa_attribute(<property number>, <property state>)
``` 
where `inst` is the result the `open_resource` method, `<property number>` is the constant for the attribute (you can look in `visa.constants`) and `<property state>` is the state you want to set.

Many attributes has a python friendly name, but not this one. The reason is that this value is automatically set to True if you set the `read_termination` value to something different from an empty string.

Please provide code if this does not answer your question.

**Comment by joeadam** [comment]
Ah,
My error message was actually the type of property number.  I had assumed that the property number was actually a string.
All working now.
Thanks for the quick reply – much appreciated!

**Comment by hgrecco** [comment]
Then I am closing this. Great that I could help
